name: Node.js CI 

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Zeet Run
        uses: zeet-co/zeet-run-action@v1
        with:
          deploy_key: ${{ secrets.ZEET_DEPLOY_KEY }}
          project: zeet-demo/zeet-demo-node-actions
          command: ls -al
          build: true
          wait: true

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zeetco/node-github-actions:${{ github.sha }}

      - name: Zeet Deploy
        uses: zeet-co/zeet-deploy-action@v2
        with:
          deploy_key: ${{ secrets.ZEET_DEPLOY_KEY }}
          project: zeet-demo/zeet-demo-node-actions
          image: zeetco/node-github-actions:${{ github.sha }}
          branch: ${{ github.ref_name }}
          wait: false
